### ISSUE TITLE
compiler asciidoc does not work on Windows

### ISSUE THREAD

**Issue by cricrazy** [dahu/vim-asciidoc#13]
Hi Dahu, 

I am using Vim-asciidoc with GVim on Windows 7. I cannot compile using the 

> :compiler asciidoc (or asciidoctor)

It gives the following error. 

> E666: compiler not supported: asciidoc

Can you please help? Syntax highlighting is working fine.

**Comment by dahu** [comment]
E666 would suggest that vim-asciidoc isn't fully installed... 
How did you install vim-asciidoc?
I am not familiar with Windows, so I can't advise further.
Getting Asciidoc[tor] to work on Windows is an effort in itself.
