### ISSUE TITLE
No newline is added when `textwidth` is reached

### ISSUE THREAD

**Issue by allannielsen** [dahu/vim-asciidoc#19]
When writing a paragraph, vim normally insert a newline when I reach the `textwidth` limit, but that does not seem to work with this plug in.

Did I miss a configuration setting, and/or is this intended behavioural?

**Comment by allannielsen** [comment]
Works perfect! Thanks a lot for fixing my issue.

**Comment by dahu** [comment]
You're welcome. I do wonder if it will cause some grief with vim-internal formatting in insert mode conflicting with the asciidoc-specific formatting offered by the mapped gq command. A bridge to cross another day.
