### ISSUE TITLE
Format not working with utf-8 text

### ISSUE THREAD

**Issue by valir** [dahu/vim-asciidoc#5]
Hello,

Please consider this piece of text:
Și cum spuneam, stăteam toată ziua în pătul și citeam. Luam cărți de la verișorii mei. Avea destule așa că aveam ce citi pe tot timpul vacanței de vară, care ținea 3 luni pe atunci.

I place the cursor on the starting Ș and press Q. Instead of formatting the text, vim-asciidoc display this error:

vim-asciidoc: unknown block on 77: don't know how to format: Și cum spuneam, st<c4>...

Any ideau about this error?

**Comment by valir** [comment]
Thanks for the quick reaction!

I just updated the plug-in, then retried the same paragraph and now I get this - notice I have more lines of errors.

vim-asciidoc: unknown block on 77: don't know how to format: Și cum spuneam, st<c4>...                                                                     
Error detected while processing function <SNR>143_Q:
line   25:
E354: Invalid register name: '*'
Press ENTER or type command to continue

**Comment by dahu** [comment]
Ah... your vim doesn't have xterm clipboard support.
I will fix it, but not right now.

For now, you can comment out lines: 159 and 182 in ftplugin/asciidoc.vim

**Comment by valir** [comment]
It now works. I double checked the git update - seems that NeoBundleUpdate command did not update correctly. I manually updated the plugin. I also installed gvim, which also provides vim with xterm support (I'm using Arch).

Thanks,
