### ISSUE TITLE
[Question] Ultisnips variable expansion

### ISSUE THREAD

**Issue by sethwoodworth** [dahu/vim-asciidoc#9]
In your provided snippets for asciidoc, you [expand the vim global variables](https://github.com/dahu/vim-asciidoc/blob/f61e43cb3e5a9baf9ae5147af96dec920b36740b/UltiSnips/asciidoc.snippets#L8) of `g:username` and `g:email`.  Are these variables conventions from UltiSnips, from VIM, or from this project.  They are sound defaults, I'd either like to track down their source, or add them to the README here.

**Comment by dahu** [comment]
They come from https://github.com/aperezdc/vim-template which I use in https://github.com/dahu/Area-41.
